# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

uint32 COORDINATE_SYSTEM_ETRS89 = 0
uint32 COORDINATE_SYSTEM_NAD83 = 1
uint32 COORDINATE_SYSTEM_ITRF2000 = 2
uint32 COORDINATE_SYSTEM_WGS84 = 3
uint32 COORDINATE_SYSTEM_LOCAL = 4
uint64 COORDINATE_SYSTEM_UNAVAILABLE = 255

uint32 type