# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

uint8 STATE_UNKNOWN=0
uint8 STATE_INIT=1
uint8 STATE_DISARMED=2
uint8 STATE_ARMED=3
uint8 STATE_RUNNING=4
uint8 STATE_POSTRUN=5
uint8 STATE_ABORTING=6
uint8 STATE_REMOTE_CONTROL=7
uint8 STATE_PRE_ARMING=8
uint8 STATE_PRE_RUNNING=9
uint8 state