# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

iso_msgs/OSEMIds desired_id
geographic_msgs/GeoPoint coordinate_system_origin
float64 coordinate_system_rotation_rad
iso_msgs/CoordinateSystem coordinate_system_type
builtin_interfaces/Duration current_time
iso_msgs/OSEMDeviations max_deviation
float64 min_required_positioning_accuracy_m
iso_msgs/TestMode test_mode
builtin_interfaces/Duration heab_timeout
iso_msgs/OSEMMonrRate rate
iso_msgs/OSEMTimeServer time_server
